package pack;
// Generated 20 Jan, 2020 8:47:06 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categorysubcategory generated by hbm2java
 */
@Entity
@Table(name = "categorysubcategory", catalog = "etourfinal")
public class Categorysubcategory implements java.io.Serializable {

	private int catsubid;
	private Integer categoryid;
	private String categoryname;
	private String categoryimage;
	private Integer subcategoryid;
	private String subcategoryname;
	private String subcategoryimage;
	private String eofflag;
	private Set<Packagecompletedetail> packagecompletedetails = new HashSet<Packagecompletedetail>();

	public Categorysubcategory() {
	}

	public Categorysubcategory(int catsubid) {
		this.catsubid = catsubid;
	}

	public Categorysubcategory(int catsubid, Integer categoryid, String categoryname, String categoryimage,
			Integer subcategoryid, String subcategoryname, String subcategoryimage, String eofflag,
			Set<Packagecompletedetail> packagecompletedetails) {
		this.catsubid = catsubid;
		this.categoryid = categoryid;
		this.categoryname = categoryname;
		this.categoryimage = categoryimage;
		this.subcategoryid = subcategoryid;
		this.subcategoryname = subcategoryname;
		this.subcategoryimage = subcategoryimage;
		this.eofflag = eofflag;
		this.packagecompletedetails = packagecompletedetails;
	}

	@Id

	@Column(name = "catsubid", unique = true, nullable = false)
	public int getCatsubid() {
		return this.catsubid;
	}

	public void setCatsubid(int catsubid) {
		this.catsubid = catsubid;
	}

	@Column(name = "categoryid")
	public Integer getCategoryid() {
		return this.categoryid;
	}

	public void setCategoryid(Integer categoryid) {
		this.categoryid = categoryid;
	}

	@Column(name = "categoryname", length = 250)
	public String getCategoryname() {
		return this.categoryname;
	}

	public void setCategoryname(String categoryname) {
		this.categoryname = categoryname;
	}

	@Column(name = "categoryimage", length = 250)
	public String getCategoryimage() {
		return this.categoryimage;
	}

	public void setCategoryimage(String categoryimage) {
		this.categoryimage = categoryimage;
	}

	@Column(name = "subcategoryid")
	public Integer getSubcategoryid() {
		return this.subcategoryid;
	}

	public void setSubcategoryid(Integer subcategoryid) {
		this.subcategoryid = subcategoryid;
	}

	@Column(name = "subcategoryname", length = 250)
	public String getSubcategoryname() {
		return this.subcategoryname;
	}

	public void setSubcategoryname(String subcategoryname) {
		this.subcategoryname = subcategoryname;
	}

	@Column(name = "subcategoryimage", length = 250)
	public String getSubcategoryimage() {
		return this.subcategoryimage;
	}

	public void setSubcategoryimage(String subcategoryimage) {
		this.subcategoryimage = subcategoryimage;
	}

	@Column(name = "eofflag", length = 250)
	public String getEofflag() {
		return this.eofflag;
	}

	public void setEofflag(String eofflag) {
		this.eofflag = eofflag;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categorysubcategory")
	public Set<Packagecompletedetail> getPackagecompletedetails() {
		return this.packagecompletedetails;
	}

	public void setPackagecompletedetails(Set<Packagecompletedetail> packagecompletedetails) {
		this.packagecompletedetails = packagecompletedetails;
	}

}
