package pack;
// Generated 20 Jan, 2020 8:47:06 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * Customerdetail generated by hbm2java
 */
@Entity
@Table(name = "customerdetail", catalog = "etourfinal")
public class Customerdetail implements java.io.Serializable {

	private int customerid;
	private String customername;
	private String email;
	private String password;
	private String address1;
	private String address2;
	private String city;
	private String state;
	private Short pin;
	private String telno;
	private String mobileno;
	private Date registrationdate;
//	private Set<Bookingdetail> bookingdetails = new HashSet<Bookingdetail>();

	public Customerdetail() {
	}

	public Customerdetail(int customerid) {
		this.customerid = customerid;
	}

	public Customerdetail(int customerid, String customername, String email, String password, String address1,
			String address2, String city, String state, Short pin, String telno, String mobileno,
			Date registrationdate/* ,Set<Bookingdetail> bookingdetails */) {
		this.customerid = customerid;
		this.customername = customername;
		this.email = email;
		this.password = password;
		this.address1 = address1;
		this.address2 = address2;
		this.city = city;
		this.state = state;
		this.pin = pin;
		this.telno = telno;
		this.mobileno = mobileno;
		this.registrationdate = registrationdate;
//		this.bookingdetails = bookingdetails;
	}

	@Id

	@Column(name = "customerid", unique = true, nullable = false)
	public int getCustomerid() {
		return this.customerid;
	}

	public void setCustomerid(int customerid) {
		this.customerid = customerid;
	}

	@Column(name = "customername", length = 250)
	public String getCustomername() {
		return this.customername;
	}

	public void setCustomername(String customername) {
		this.customername = customername;
	}

	@Column(name = "email", length = 250)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", length = 250)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "address1", length = 250)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "address2", length = 250)
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "city", length = 250)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state", length = 250)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "pin")
	public Short getPin() {
		return this.pin;
	}

	public void setPin(Short pin) {
		this.pin = pin;
	}

	@Column(name = "telno", length = 10)
	public String getTelno() {
		return this.telno;
	}

	public void setTelno(String telno) {
		this.telno = telno;
	}

	@Column(name = "mobileno", length = 10)
	public String getMobileno() {
		return this.mobileno;
	}

	public void setMobileno(String mobileno) {
		this.mobileno = mobileno;
	}

	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-mm-yyyy")
	@Temporal(TemporalType.DATE)
	@Column(name = "registrationdate", length = 10)
	public Date getRegistrationdate() {
		return this.registrationdate;
	}

	public void setRegistrationdate(Date registrationdate) {
		this.registrationdate = registrationdate;
	}

	/*
	 * @OneToMany(fetch = FetchType.LAZY, mappedBy = "customerdetail") public
	 * Set<Bookingdetail> getBookingdetails() { return this.bookingdetails; }
	 * 
	 * public void setBookingdetails(Set<Bookingdetail> bookingdetails) {
	 * this.bookingdetails = bookingdetails; }
	 */

}
