package pack;
// Generated 20 Jan, 2020 8:47:06 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Datepackagedetail generated by hbm2java
 */
@Entity
@Table(name = "datepackagedetail", catalog = "etourfinal")
public class Datepackagedetail implements java.io.Serializable {

	private int datepackageid;
	private Packagecompletedetail packagecompletedetail;
	private Date startdate;
	private Date enddate;
	private Set<Bookingdetail> bookingdetails = new HashSet<Bookingdetail>();

	public Datepackagedetail() {
	}

	public Datepackagedetail(int datepackageid) {
		this.datepackageid = datepackageid;
	}

	public Datepackagedetail(int datepackageid, Packagecompletedetail packagecompletedetail, Date startdate,
			Date enddate, Set<Bookingdetail> bookingdetails) {
		this.datepackageid = datepackageid;
		this.packagecompletedetail = packagecompletedetail;
		this.startdate = startdate;
		this.enddate = enddate;
		this.bookingdetails = bookingdetails;
	}

	@Id

	@Column(name = "datepackageid", unique = true, nullable = false)
	public int getDatepackageid() {
		return this.datepackageid;
	}

	public void setDatepackageid(int datepackageid) {
		this.datepackageid = datepackageid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "packageid")
	public Packagecompletedetail getPackagecompletedetail() {
		return this.packagecompletedetail;
	}

	public void setPackagecompletedetail(Packagecompletedetail packagecompletedetail) {
		this.packagecompletedetail = packagecompletedetail;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "startdate", length = 10)
	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "enddate", length = 10)
	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "datepackagedetail")
	public Set<Bookingdetail> getBookingdetails() {
		return this.bookingdetails;
	}

	public void setBookingdetails(Set<Bookingdetail> bookingdetails) {
		this.bookingdetails = bookingdetails;
	}

}
