package pack;
// Generated 20 Jan, 2020 8:47:06 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Packagecompletedetail generated by hbm2java
 */
@Entity
@Table(name = "packagecompletedetail", catalog = "etourfinal")
public class Packagecompletedetail implements java.io.Serializable {

	private int packageid;
	private Categorysubcategory categorysubcategory;
	private String tourname;
	private String tourimage;
	private String description;
	private Set<Pricedetail> pricedetails = new HashSet<Pricedetail>();
	private Set<Itinerary> itineraries = new HashSet<Itinerary>();
	private Set<Bookingdetail> bookingdetails = new HashSet<Bookingdetail>();
	private Set<Datepackagedetail> datepackagedetails = new HashSet<Datepackagedetail>();

	public Packagecompletedetail() {
	}

	public Packagecompletedetail(int packageid) {
		this.packageid = packageid;
	}

	public Packagecompletedetail(int packageid, Categorysubcategory categorysubcategory, String tourname,
			String tourimage, String description, Set<Pricedetail> pricedetails, Set<Itinerary> itineraries,
			Set<Bookingdetail> bookingdetails, Set<Datepackagedetail> datepackagedetails) {
		this.packageid = packageid;
		this.categorysubcategory = categorysubcategory;
		this.tourname = tourname;
		this.tourimage = tourimage;
		this.description = description;
		this.pricedetails = pricedetails;
		this.itineraries = itineraries;
		this.bookingdetails = bookingdetails;
		this.datepackagedetails = datepackagedetails;
	}

	@Id

	@Column(name = "packageid", unique = true, nullable = false)
	public int getPackageid() {
		return this.packageid;
	}

	public void setPackageid(int packageid) {
		this.packageid = packageid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "catsubid")
	public Categorysubcategory getCategorysubcategory() {
		return this.categorysubcategory;
	}

	public void setCategorysubcategory(Categorysubcategory categorysubcategory) {
		this.categorysubcategory = categorysubcategory;
	}

	@Column(name = "tourname", length = 250)
	public String getTourname() {
		return this.tourname;
	}

	public void setTourname(String tourname) {
		this.tourname = tourname;
	}

	@Column(name = "tourimage", length = 250)
	public String getTourimage() {
		return this.tourimage;
	}

	public void setTourimage(String tourimage) {
		this.tourimage = tourimage;
	}

	@Column(name = "description", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "packagecompletedetail")
	public Set<Pricedetail> getPricedetails() {
		return this.pricedetails;
	}

	public void setPricedetails(Set<Pricedetail> pricedetails) {
		this.pricedetails = pricedetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "packagecompletedetail")
	public Set<Itinerary> getItineraries() {
		return this.itineraries;
	}

	public void setItineraries(Set<Itinerary> itineraries) {
		this.itineraries = itineraries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "packagecompletedetail")
	public Set<Bookingdetail> getBookingdetails() {
		return this.bookingdetails;
	}

	public void setBookingdetails(Set<Bookingdetail> bookingdetails) {
		this.bookingdetails = bookingdetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "packagecompletedetail")
	public Set<Datepackagedetail> getDatepackagedetails() {
		return this.datepackagedetails;
	}

	public void setDatepackagedetails(Set<Datepackagedetail> datepackagedetails) {
		this.datepackagedetails = datepackagedetails;
	}

}
