package pack;
// Generated 20 Jan, 2020 8:47:06 PM by Hibernate Tools 5.1.10.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Passengerdetail generated by hbm2java
 */
@Entity
@Table(name = "passengerdetail", catalog = "etourfinal", uniqueConstraints = @UniqueConstraint(columnNames = "passengeridno"))
public class Passengerdetail implements java.io.Serializable {

	private Integer passengerid;
	private Bookingdetail bookingdetail;
	private String passengername;
	private Date passengerdob;
	private String roomtype;
	private Integer cost;
	private String passengeriddocument;
	private String passengeridno;
	private String passengersex;
	private String passengeremail;
	private Set<Bookingdetail> bookingdetails = new HashSet<Bookingdetail>();

	public Passengerdetail() {
	}

	public Passengerdetail(Bookingdetail bookingdetail, String passengername, Date passengerdob, String roomtype,
			Integer cost, String passengeriddocument, String passengeridno, String passengersex, String passengeremail,
			Set<Bookingdetail> bookingdetails) {
		this.bookingdetail = bookingdetail;
		this.passengername = passengername;
		this.passengerdob = passengerdob;
		this.roomtype = roomtype;
		this.cost = cost;
		this.passengeriddocument = passengeriddocument;
		this.passengeridno = passengeridno;
		this.passengersex = passengersex;
		this.passengeremail = passengeremail;
		this.bookingdetails = bookingdetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "passengerid", unique = true, nullable = false)
	public Integer getPassengerid() {
		return this.passengerid;
	}

	public void setPassengerid(Integer passengerid) {
		this.passengerid = passengerid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bookingid")
	public Bookingdetail getBookingdetail() {
		return this.bookingdetail;
	}

	public void setBookingdetail(Bookingdetail bookingdetail) {
		this.bookingdetail = bookingdetail;
	}

	@Column(name = "passengername", length = 250)
	public String getPassengername() {
		return this.passengername;
	}

	public void setPassengername(String passengername) {
		this.passengername = passengername;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "passengerdob", length = 10)
	public Date getPassengerdob() {
		return this.passengerdob;
	}

	public void setPassengerdob(Date passengerdob) {
		this.passengerdob = passengerdob;
	}

	@Column(name = "roomtype", length = 250)
	public String getRoomtype() {
		return this.roomtype;
	}

	public void setRoomtype(String roomtype) {
		this.roomtype = roomtype;
	}

	@Column(name = "cost")
	public Integer getCost() {
		return this.cost;
	}

	public void setCost(Integer cost) {
		this.cost = cost;
	}

	@Column(name = "passengeriddocument", length = 250)
	public String getPassengeriddocument() {
		return this.passengeriddocument;
	}

	public void setPassengeriddocument(String passengeriddocument) {
		this.passengeriddocument = passengeriddocument;
	}

	@Column(name = "passengeridno", unique = true, length = 250)
	public String getPassengeridno() {
		return this.passengeridno;
	}

	public void setPassengeridno(String passengeridno) {
		this.passengeridno = passengeridno;
	}

	@Column(name = "passengersex", length = 250)
	public String getPassengersex() {
		return this.passengersex;
	}

	public void setPassengersex(String passengersex) {
		this.passengersex = passengersex;
	}

	@Column(name = "passengeremail", length = 250)
	public String getPassengeremail() {
		return this.passengeremail;
	}

	public void setPassengeremail(String passengeremail) {
		this.passengeremail = passengeremail;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "passengerdetail")
	public Set<Bookingdetail> getBookingdetails() {
		return this.bookingdetails;
	}

	public void setBookingdetails(Set<Bookingdetail> bookingdetails) {
		this.bookingdetails = bookingdetails;
	}

}
